CREATE TABLE IF NOT EXISTS messages (
    id SERIAL PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    class_id SMALLINT NOT NULL,
    roadmap_id SMALLINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

